package domain;

public enum LabelType {
    PID, TSINT, TSVOID, VARDEC, ARRDEC, FUNDEC, FUNENDPARS, FUNJPCALLER, PARID, VOIDPARERR, SINGLEVOIDPAR, SETPAR, WITHBRCK, WITHOUTBRCK, CONTINUE, BREAK, IF_SAVE,
    JP_SAVE, ENDIF, WH_LABEL, WH_SAVE, ENDWH, VOIDRETURN, RETURN, SYMBOL, ASSIGN, GETARR, LTOREQ, PLORMI, PLUS, MINUS, LT, EQ, FMULT, FMINUS, NUM, FUNCALL, FUNCALLJP,
    ZEROARGNUM, COUNTARG
}
