package domain;

public enum TerminalType {
    EOF, EPSILON, ID, INT, VOID, SEMICOLON, BL, BR, NUM, PL, PR, COMMA, KL, KR, CONTINUE, BREAK, IF, ELSE, WHILE,
    RETURN, SWITCH, CASE, DEFAULT, COLON, ASSIGN, PLUS, MINUS, LESS, EQ, MULTIPLE,
}
