package domain;

public enum TerminalType {
    PR, PL, ID, COMMA, VOID, INT, BR, BL, NUM, MINUS, PLUS, MULT, LESS, EQ, ASGN, COLON, DEFAULT, CASE, KR, KL,
    SWITCH, SEMICOLON, RETURN, WHILE, ELSE, IF, CONTINUE, BREAK, EOF, TREEFLAG
}
